// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvhWh9pM4DLwwWUK7ncHA2gCE76owwZ_s',
    appId: '1:319934429468:web:cbe823fde94a8ca44fe2d9',
    messagingSenderId: '319934429468',
    projectId: 'go-gallery-87a9e',
    authDomain: 'go-gallery-87a9e.firebaseapp.com',
    storageBucket: 'go-gallery-87a9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDjIe0HUTWHUsBLYePJF-gHUlHJUbl8Y',
    appId: '1:44824767625:android:bcf9bb2f3a9a1feb8fea58',
    messagingSenderId: '44824767625',
    projectId: 'roadtrip-router',
    storageBucket: 'roadtrip-router.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIJi52rgjOrMdJUZiz66Zd9bgxJkqGLr8',
    appId: '1:44824767625:ios:8ba9dd75bf857d2f8fea58',
    messagingSenderId: '44824767625',
    projectId: 'roadtrip-router',
    storageBucket: 'roadtrip-router.appspot.com',
    iosClientId: '44824767625-rsf65624csv5256fifllb3ndm512v7fo.apps.googleusercontent.com',
    iosBundleId: 'com.c25kenneth.goGallery',
  );

}